parameters:
  cti_mongo_service.connection_wrapper.class: CTI\MongoServiceBundle\MongoConnectionWrapper
  cti_mongo_service.client.class: CTI\MongoServiceBundle\CtiMongoClient

  mongo_retries: 5
  mongo_url: dummy_mongo_url
  mongo_host: dummy_mongo_host
  mongo_user:
  mongo_pass:
  mongo_db: dummy_mongo_db
  mongo_coll: dummy_mongo_coll
  mongo_sleep_before_reconnect: 250
  mongo_read_preference: primary # primary, primaryPreferred, secondary, secondaryPreferred, nearest

services:

  cti_mongo_service.connection_wrapper:
    class: %cti_mongo_service.connection_wrapper.class%
    arguments: [%mongo_host%, "@=container.hasParameter('mongo_port') ? parameter('mongo_port') : '27017'", %mongo_db%, %mongo_user%, %mongo_pass%, %mongo_retries%, "@=container.hasParameter('mongo_replicaset') ? parameter('mongo_replicaset') : ''"]
    calls:
      - [ setSleepTime, [%mongo_sleep_before_reconnect%] ]
      - [ setReadPreference, [%mongo_read_preference%] ]

  cti_mongo_service.client:
    class : %cti_mongo_service.client.class%
    arguments : [ @cti_mongo_service.connection_wrapper, %mongo_db%, %mongo_coll% ]
