parameters:
  cti_mongo_service.client.class : CTI\MongoServiceBundle\MongoService
  cti_mongo_service.manager.class : CTI\MongoServiceBundle\MongoManager

  mongo_retries: 5
  mongo_url: dummy_mongo_url
  mongo_host: dummy_mongo_host
  mongo_port: dummy_mongo_port
  mongo_user:
  mongo_pass:
  mongo_db: dummy_mongo_db
  mongo_coll: dummy_mongo_coll

services:

  cti_mongo_service.client:
    class: %cti_mongo_service.client.class%
    arguments: [%mongo_host%, %mongo_port%, %mongo_db%, %mongo_user%, %mongo_pass%, %mongo_retries%]

  cti_mongo_service.manager:
    class : %cti_mongo_service.manager.class%
    arguments : [ @cti_mongo_service.client, %mongo_db%, %mongo_coll% ]
